name: pr-aws-pulumi-bucket
on:
  pull_request:
    paths:
      - 'resources/aws-pulumi-bucket/**'
      - '.github/workflows/pr-aws-pulumi-bucket.yml'
    
  workflow_dispatch:

jobs:
  preview:
    name: Preview - ${{ matrix.zone }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        zone: ["dev", "test-us", "prod-us", "prod-eu"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@v1
      - run: npm install
        working-directory: resources/aws-pulumi-bucket
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: ${{ matrix.zone }}
          work-dir: resources/aws-pulumi-bucket
          comment-on-pr: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
